### ISSUE TITLE
Flicker in Storyboard Rendering

### ISSUE THREAD

**Issue by jayliu50** [werwack/storyliner-support#14] opened 2024-09-03 07:53 UTC
## Infos on the context
- **Add-on edition:** StoryLiner Storyboard
- **Add-on version:** V 1.1.30
- Blender version, from installer or from zip:  4.2.1 ZIP
- Blender was launched in Admin mode? No
- **OS:** Windows 10
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): Don't Know

## Describe the bug
Renders of storyboard have flickers. Upon inspecting frames, there are indeed blank frames. Perhaps this is due to bad stitching or something? In the example file below, there is only 1 shot, so the problem isn't when moving from shot to shot.

## To Reproduce
1. Open [flicker.zip](https://github.com/user-attachments/files/16845276/flicker.zip). 
2. Render All
3. BUG: note that the resulting video (see screenshots below) have missing frames at 30 and 120.

## Expected behavior
Render all the frames!

## Additional context, screenshots...
Here are 3 consecutive frames:
![image](https://github.com/user-attachments/assets/70f11f85-fa54-4ab9-b4d2-f67d60327a31)
![image](https://github.com/user-attachments/assets/5895383f-a42a-4623-b33b-0a2875edb8ea)
![image](https://github.com/user-attachments/assets/92e7a8ff-7ce5-44c1-aa34-87c87a5a25f3)

See the attached video. The blank frames happen at 30 and 120. 

https://github.com/user-attachments/assets/a3960c72-bdab-41d0-9a7f-37f5e1fd3989

Update:
One a separate occasion when trying to render an image sequence, we see the same thing happen even with the intermediate images:

![image](https://github.com/user-attachments/assets/f6ddb3c0-cca6-48c5-9ea9-46aca1d7fd20)

**Comment by werwack** [comment] 2024-09-03 16:45
Yep, I know 😥. This is a Blender 4.2 specific bug. And since you said you are on 4.2.1 it looks like it hasn't been fixed on the latest release 😥😥
I'm pretty sure the rendering works well on 4.1. Should you have time, I would appreciate if you can confirm that.
Thanks a lot

**Comment by jayliu50** [comment] 2024-09-03 17:15
4.1 seems fine, confirmed. Thanks for your work!

**Comment by werwack** [comment] 2024-09-03 19:46
Thank you. I'll enter a bug on Blender side tomorrow.

**Comment by werwack** [comment] 2024-09-06 21:36
The issue has been reproduced and a ticket opened on Project.Blender.org:
[https://projects.blender.org/blender/blender/issues/127271](https://projects.blender.org/blender/blender/issues/127271)

As a workaround in StoryLiner, the rendering can be done in Software mode instead of OpenGl.

**Comment by werwack** [comment] 2024-09-09 10:50
Hi @jayliu50 
The Blender dev team did a fix, it should be in 4.2.2.

**Closed** 2024-11-25 08:29 UTC
Labels: bug, Blender 4.2, done
